<?php

namespace TimeDude\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * 
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function findAllAdministrators() {

       return null;
    }

}
