<?php

namespace TimeDude\Bundle\TimeDudeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * 
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeDudeUserRepository extends EntityRepository {

    public function findAllAdministrators() {

       return null;
    }

}
